name: NodeCI

on:
  - push
jobs:
  my-job:
    runs-on: ubuntu-latest 
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          make install
      - name: Run Linter
        run: |
          make lint
      - name: Deploy
        run: |
          make deploy
